# Generated by Django 4.2.1 on 2023-06-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('date', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('parent_number', models.BigIntegerField()),
                ('postal', models.BigIntegerField()),
                ('referal', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
