# Generated by Django 4.2.1 on 2023-06-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('heading', models.CharField(max_length=30)),
                ('sub_heading', models.CharField(max_length=30)),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('fees', models.IntegerField()),
                ('offerfees', models.IntegerField(blank=True, default='0')),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
