# Generated by Django 4.2.1 on 2023-06-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
