# Generated by Django 4.2.1 on 2023-06-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_course_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_card',
            new_name='Course_details',
        ),
    ]
