# Generated by Django 4.2.1 on 2023-06-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_rename_course_card_course_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foot',
        ),
    ]
